version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: blurer
      POSTGRES_USER: blurer
      POSTGRES_DB: blurer
    ports:
      - 5432:5432
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./storage/:/storage/
    environment:
      DATABASE_URL: "postgres://blurer:blurer@db:5432/blurer?sslmode=disable"
    depends_on:
      - db